### PR TITLE
all notebooks running with required changes for v0.10.0rc0

### PR DESCRIPTION
**Pull request by claytantor**
The example as committed to master has an incomplete requirements and installation procedure for it to run without errors. This commit is intended to enhance the example for all notebooks so it is compatible with the v0.10.0rc0 release of tensorflow.
- used dtype=np.float32 on linspaces
- enhanced requirements file
- added installation instructions

Hope this helps.

### CODE REVIEW

**Comment by claytantor** [comment]
That didn't happen to me when I ran pip install -r requirements.txt. what
is in the pr is exactly what was needed to get the example to work in a
virtualenv. The order matters also.

**Comment by md-mq** [comment]
I just tried again, the correct requirements.txt should only contain these packages:

```
scipy==0.18.1
pandas==0.18.1
tensorflow==0.10.0rc0
matplotlib==1.5.1
jupyter==1.0.0
scikit-learn==0.18
```

If you have some time, can you check the requirements again, and update the PR?

thanks.

**Comment by claytantor** [comment]
I will try and report back.

**Comment by md-mq** [comment]
@claytantor Thank you very much.

**Pull request merged**
